import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Header from "@/components/Header";
import dynamic from "next/dynamic";
import Calendardates from "@/components/calender";
import Footer from "@/components/Footer";
import Reverseshow from "@/components/reverse-slide";
import Slidesshow from "@/components/new-slides";

export default function BookAppointment() {
  return (
    <>
      <Head>
        <title>playroom-kids Theme</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="book-an-app">
        <header>
          <div className="navbar navbar-grid">
            <div className="logo">
              <Link href="/">
                <img src="images/homepage/header-logo.png" alt="Logo" />
              </Link>
            </div>

            <div id="mySidepanel" className="sidepanel">
              <a
                href="javascript:void(0)"
                className="closebtn"
                onClick={() => closeNav()}
              ></a>
              <a className="no--border" href="#home">
                Home
              </a>
              <a href="#" className="nav-link">
                Pages
              </a>
              <a href="#" className="nav-link">
                Events{" "}
              </a>
              <a href="#" className="nav-link">
                Blog
              </a>
              <a href="#" className="nav-link">
                Shop
              </a>
              <a href="#" className="nav-link">
                Landing
              </a>
            </div>
            <button className="openbtn open-btn-grid" onClick={() => openNav()}>
              ...
            </button>
          </div>
          <div className="navbar navbar--ROP">
            <div className="logo">
              <Link href="/">
                <img src="images/homepage/header-logo.png" alt="Logo" />
              </Link>
            </div>

            <div className="nav-links">
              <ul className="no-bullets">
                <li>
                  <Link href="/">Home</Link>
                </li>

                <li>
                  <Link href="/events">Events</Link>
                </li>
                <li>
                  <Link href="/blog">Blog</Link>
                </li>
                <li>
                  <Link href="/shop">Shop</Link>
                </li>
                <li>
                  <Link href="/grid-view">Grid Home</Link>
                </li>
                <li>
                  <Link href="/animator">Animator</Link>
                </li>
                <li>
                  <Link href="/rules--of--play">Rules Of Play</Link>
                </li>
              </ul>
            </div>
          </div>
        </header>
        <div className=" Book--hero ">
          <p className="pink"> Welcome To Playroom </p>
          <h1>Book A Party</h1>
        </div>
        <div className="calendar--flexbox">

        <div className="calendar">
            <Calendardates/>
        </div>
        <div className="event-play-section work--hours">
            <h2>Check out our</h2>
            <h1>
              <span className="first-color">Work </span> 
              <span className="second-color">Hours & </span> 
              <span className="third-color"> Days </span> 
            </h1>
            <div className="work--day--flx"> 
            <div className="work-days">
              <div className="work-day">
              <h3>Mon - Wed </h3>
              </div>
              <div className="emplty--flx"></div>
              <div className="work-time">
               <p>9:00 AM - 12:00 PM</p>
              </div>
            </div>
              <div className="work-days">
              <div className="work-day">
              <h3>Thu - Fri  </h3>
              </div>
              <div className="emplty--flx"></div>
              <div className="work-time">
               <p>9:00 AM - 12:00 PM</p>
              </div>
            </div>
            <div className="work-days">
              <div className="work-day">
              <h3>Saturday  </h3>
              </div>
              <div className="emplty--flx"></div>
              <div className="work-time">
               <p>9:00 AM - 12:00 PM</p>
              </div>
              </div>
            <div className="work-days">
              <div className="work-day">
              <h3>Sunday </h3>
              </div>
              <div className="emplty--flx"></div>
              <div className="work-time">
               <p>CLOSED</p>
              </div>
              </div>
            </div>
            <p>
               Suas quas veniam at eam, vix an vide deleniti dissentiet, eam cu semper oblique placerat pri no.
            </p>
            </div>
        </div>
        <div className="slides">
          < Reverseshow />
          <Slidesshow />
        </div>
        </main>
        <div className="footer-sec">
        <Footer />
      </div>
        </>
  );
}
