import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Header from "@/components/Header";
import dynamic from "next/dynamic";
import Footer from "@/components/Footer";
export default function Animator() {
  return (
    <>
      <Head>
        <title>playroom-kids Theme</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="Contacts">
        <header>
          <div className="navbar navbar-grid">
            <div className="logo">
              <Link href="/">
                <img src="images/homepage/header-logo.png" alt="Logo" />
              </Link>
            </div>

            <div id="mySidepanel" className="sidepanel">
              <a
                href="javascript:void(0)"
                className="closebtn"
                onClick={() => closeNav()}
              ></a>
              <a className="no--border" href="#home">
                Home
              </a>
              <a href="#" className="nav-link">
                Pages
              </a>
              <a href="#" className="nav-link">
                Events{" "}
              </a>
              <a href="#" className="nav-link">
                Blog
              </a>
              <a href="#" className="nav-link">
                Shop
              </a>
              <a href="#" className="nav-link">
                Landing
              </a>
            </div>
            <button className="openbtn open-btn-grid" onClick={() => openNav()}>
              ...
            </button>
          </div>
          <div className="navbar navbar--ROP">
            <div className="logo">
              <Link href="/">
                <img src="images/homepage/header-logo.png" alt="Logo" />
              </Link>
            </div>

            <div className="nav-links">
              <ul className="no-bullets">
                <li>
                  <Link href="/">Home</Link>
                </li>

                <li>
                  <Link href="/events">Events</Link>
                </li>
                <li>
                  <Link href="/blog">Blog</Link>
                </li>
                <li>
                  <Link href="/shop">Shop</Link>
                </li>
                <li>
                  <Link href="/grid-view">Grid Home</Link>
                </li>
                <li>
                  <Link href="/animator">Animator</Link>
                </li>
                <li>
                  <Link href="/rules--of--play">Rules Of Play</Link>
                </li>
              </ul>
            </div>
          </div>
        </header>
        <div className="map--none">
          <iframe
            className="map--full map--about"
            src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d24175.93406743113!2d-73.989465!3d40.762206!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sin!4v1683521937515!5m2!1sen!2sin"
            width="450
"
            height="550"
            style={{ border: "0" }}
            allowfullscreen=""
            loading="lazy"
            referrerpolicy="no-referrer-when-downgrade"
          ></iframe>
        </div>
    <div className="full-flxbox">

        <section className="qodef-section">

          <div className="intouch">
            <h2>
              <span className="first-color">Get </span>
              <span className="second-color">In Touch</span>
              <span className="third-color"> Today</span>
            </h2>
            <p>
              Suas quas veniam at eam, vix an vide deleniti, oblique placerat
              pri no. Vel id prima reprimique dissentie, eamcu semper albucius.
              Sed no posse semper. In populo legimus vocibus sit, doctu anil
              eun. Partemusto animal euismod noluisse has in, persius deserunt.
            </p>
          </div>
          <div className="contact--details">
            <h2>Contact Details</h2>
            <div className="contacts--flx">
              <div className="contact--details-flx1">
                <div className="contact-item">
                  <div className="contact-data">Address :</div>
                  <div className="contact-text width-47%">
                    24 Maples, Roslyn, NY 11576
                  </div>
                </div>
                <div className="contact-item">
                  <div className="contact-data">Website:</div>
                  <div className="contact-text">
                    https://qodeinteractive.com/
                  </div>
                </div>
                <div className="contact-item">
                  <div className="contact-data">Venue:</div>
                  <div className="contact-text">Kids Playroom No.03</div>
                </div>
              </div>

              <div className="contact--details-flx2">
                <div className="contact-item">
                  <div className="contact-data">Organizer name:</div>
                  <div className="contact-text">Ella & Tom Grant</div>
                </div>
                <div className="contact-item">
                  <div className="contact-data">Phone:</div>
                  <div className="contact-text">+ 132024 - 232 - 024</div>
                </div>
              </div>
            </div>
          </div>
        </section>
        
        <div className="contact--img">
          <img src="images/contact-us/green-kid.jpg" alt="green kid" />
        </div>
    </div>
      </main>


      <div className="footer-sec">
        <Footer />
      </div>
    </>
  );
}
